server.port=8080
spring.application.name=fintrack-crm
spring.thymeleaf.encoding=UTF-8
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Mensagem padrao para envio (editavel aqui ou via tela)
crm.mensagem.padrao=Ola [nome], tudo bem?\n\nSegue o promocional de aniversario para voce utilizar como preferir e para o seu [veiculo] [placa]... Apenas me retorne a melhor data para agendamento.\n\nEquipe AutoTech
